	const siteData = {

  culthist: [
     {
       id: 1,
       name: "Santhi natha Temple, Venniyod",
       description: "Ancient temple dedicated to Lord Vishnu, nestled in the hills of Wayanad.",
       image: "assets/img/tirunelli.png",
       holidays: "Sun",
       timing: "10:00-18:00",
       Contact: "+91-000 000 0000",
       locationid: "1",
 	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
       distance: "10",
       rating: "4.4",
       knowmore: "./Santhi.html?id=1&cat=0",

     },

 	{
      id: 4,
      name: "Tirunelli Temple",
      description: "Ancient temple dedicated to Lord Vishnu, nestled in the hills of Wayanad.",
      image: "assets/img/tirunelli.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "899",
      rating: "4.4",
      knowmore: "./tirunelli.html?id=4&cat=0",

    },
    {
      id: 13,
      name: "Varampatta mosque",
      description: "Historic Varampatta mosque with beautiful architecture and cultural significance.",
      image: "assets/img/ghats_wayanad.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./Varampatta.html?id=13&cat=0",

    },
    {
      id: 3,
      name: "Jain Temple",
      description: "Historic Jain temple with beautiful architecture and cultural significance.",
      image: "assets/img/demo-image-01.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./jaintemple.html?id=3&cat=0",

    },
    {
      id: 12,
      name: "Seetha Lava Kusha Temple",
      description: "Temple associated with the epic Ramayana, located in a serene setting.",
      image: "assets/img/wayanad_mist.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./seethalavakushatemple.html?id=12&cat=0",

    }
  ],
  waterfalls: [
    {
      id: 5,
      name: "Meenmutty Falls",
      description: "One of the largest and most spectacular waterfalls in Wayanad.",
      image: "assets/img/falls/meenmufalls.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./meenmuttyfalls.html?id=5",

    },
    {
      id: 6,
      name: "Soochipara Falls",
      description: "Also known as Sentinel Rock Waterfalls, perfect for trekking and rock climbing.",
      image: "assets/img/falls/soojipara_falls_b_w_wayanad.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    },
    {
      id: 7,
      name: "Kanthanpara Falls",
      description: "A picturesque waterfall surrounded by lush greenery and coffee plantations.",
      image: "assets/img/falls/kanta_falls.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    }
  ],
  museums: [
    {
      id: 8,
      name: "Folklore Museum",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/tirunelli.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    },
    {
      id: 9,
      name: "Edakkal Caves",
      description: "Ancient rock shelter with prehistoric carvings and inscriptions.",
      image: "assets/img/edakkal_caves.webp",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    },
    {
      id: 10,
      name: "Ambalavayal Heritage Museum",
      description: "Displays tribal heritage and ancient artifacts from the region.",
      image: "assets/img/tea_wayanad.webp",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    }
  ],
  romantic: [
    {
      id: 11,
      name: "Karapuzhs Dam",
      description: "Karapuzhs Dam.",
      image: "assets/img/falls/meenmufalls.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    },
    {
      id: 12,
      name: "Pookode Lake",
      description: "Also known as Sentinel Rock Waterfalls, perfect for trekking and rock climbing.",
      image: "assets/img/falls/soojipara_falls_b_w_wayanad.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    },
    {
      id: 13,
      name: "Banasurasagar Dam",
      description: "A picturesque waterfall surrounded by lush greenery and coffee plantations.",
      image: "assets/img/falls/kanta_falls.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    }
  ],
  plantation: [
    {
      id: 14,
      name: "Harissons",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/plantation/tea_plantaion.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    },
    {
      id: 15,
      name: "Wayanad Tea Estate",
      description: "Expansive tea plantations with guided tours and tasting sessions.",
      image: "assets/img/plantation/tea_estate.webp",
      holidays: "Mon",
      timing: "09:00-17:00",
      Contact: "+91-111 111 1111",
      locationid: "2",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    }
  ],
  trucking: [
    {
      id: 16,
      name: "chundale",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/trucking/edakkal_caves.webp",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    },
    {
      id: 17,
      name: "Chembra Peak Trek",
      description: "Popular trekking destination with breathtaking views and a heart-shaped lake.",
      image: "assets/img/trucking/trucking.jpg",
      holidays: "None",
      timing: "06:00-17:00",
      Contact: "+91-222 222 2222",
      locationid: "3",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    }
  ],
  wildlife: [
    {
      id: 18,
      name: "Bandipur Museum",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/wildlife/Wildlife_safari_at_tholpetty_wildlife_sanctuaryjpg.avif",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    },
    {
      id: 19,
      name: "Muthanga Wildlife Sanctuary",
      description: "Sanctuary with elephants, deer, and a variety of birds in their natural habitat.",
      image: "assets/img/wildlife/pakshipathalam-bird-sanctuary-wayanad.jpg",
      holidays: "None",
      timing: "07:00-17:00",
      Contact: "+91-333 333 3333",
      locationid: "4",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    }
  ],
  farms: [
    {
      id: 20,
      name: "Ambalavayal",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/tirunelli.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["All Season"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html"
    },
    {
      id: 21,
      name: "Pepper Farm",
      description: "Experience spice cultivation and farm life in Wayanad.",
      image: "assets/img/falls/chitafalls.png",
      holidays: "None",
      timing: "08:00-18:00",
      Contact: "+91-444 444 4444",
      locationid: "5",
	  seasontovisit:["All Season"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    }
  ],
  sporting: [
        {
          id: 22,
          name: "Sports",
          description: "Ziplines.",
          image: "assets/img/tirunelli.png",
          holidays: "Sun",
          timing: "10:00-18:00",
          Contact: "+91-000 000 0000",
          locationid: "1",
     	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
          distance: "10",
          rating:"4.5",
          knowmore: "./knowmore.html",

      }
    ],
  food: [
    {
      id: 23,
      name: "Resturants",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/tirunelli.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["All Season"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    },
    {
      id: 24,
      name: "LocalCuisine",
      description: "Try authentic Kerala dishes at local eateries and food stalls.",
      image: "assets/img/heritage/chain_tree.avif",
      holidays: "None",
      timing: "11:00-23:00",
      Contact: "+91-555 555 5555",
      locationid: "6",
	  seasontovisit:["All Season"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",

    }
  ],

}