	const siteData = {

  culthist: [
    {
      id: "tirunelli",
      name: "Tirunelli Temple",
      description: "Ancient temple dedicated to Lord Vishnu, nestled in the hills of Wayanad.",
      image: "assets/img/tirunelli.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating: "4.4",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Varampatta mosque", distance: 14 },
        { name: "Jain Temple", distance: 12 },
        { name: "Seetha Lava Kusha Temple", distance: 8 },
        { name: "Meenmutty Falls", distance: 15 },
        { name: "Soochipara Falls", distance: 18 },
        { name: "Kanthanpara Falls", distance: 16 },
        { name: "Folklore Museum", distance: 11 },
        { name: "Edakkal Caves", distance: 13 },
        { name: "Ambalavayal Heritage Museum", distance: 9 },
        { name: "Pookode Lake", distance: 7 }
      ]
    },
    {
      id: "mosque1",
      name: "Varampatta mosque",
      description: "Historic Varampatta mosque with beautiful architecture and cultural significance.",
      image: "assets/img/ghats_wayanad.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Varampatta mosque", distance: 14 },
        { name: "Jain Temple", distance: 12 },
        { name: "Seetha Lava Kusha Temple", distance: 8 },
        { name: "Meenmutty Falls", distance: 15 },
        { name: "Soochipara Falls", distance: 18 },
        { name: "Kanthanpara Falls", distance: 16 },
        { name: "Folklore Museum", distance: 11 },
        { name: "Edakkal Caves", distance: 13 },
        { name: "Ambalavayal Heritage Museum", distance: 9 },
        { name: "Pookode Lake", distance: 7 }
      ]
    },
    {
      id: "temple2",
      name: "Jain Temple",
      description: "Historic Jain temple with beautiful architecture and cultural significance.",
      image: "assets/img/ghats_wayanad.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Varampatta mosque", distance: 11 },
        { name: "Seetha Lava Kusha Temple", distance: 15 },
        { name: "Soochipara Falls", distance: 9 },
        { name: "Ambalavayal Heritage Museum", distance: 13 },
        { name: "Pookode Lake", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 17 },
        { name: "Karapuzha Dam", distance: 12 },
        { name: "Banasura Sagar Dam", distance: 14 },
        { name: "Chembra Peak", distance: 10 },
        { name: "Wayanad Tea Estate", distance: 16 }
      ]
    },
    {
      id: "temple3",
      name: "Seetha Lava Kusha Temple",
      description: "Temple associated with the epic Ramayana, located in a serene setting.",
      image: "assets/img/wayanad_mist.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Jain Temple", distance: 12 },
        { name: "Tirunelli Temple", distance: 8 },
        { name: "Meenmutty Falls", distance: 15 },
        { name: "Kanthanpara Falls", distance: 11 },
        { name: "Edakkal Caves", distance: 9 },
        { name: "Folklore Museum", distance: 14 },
        { name: "Pookode Lake", distance: 13 },
        { name: "Chembra Peak", distance: 10 },
        { name: "Banasura Sagar Dam", distance: 16 }
      ]
    }
  ],
  waterfalls: [
    {
      id: "meenmutty",
      name: "Meenmutty Falls",
      description: "One of the largest and most spectacular waterfalls in Wayanad.",
      image: "assets/img/falls/meenmufalls.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Soochipara Falls", distance: 8 },
        { name: "Kanthanpara Falls", distance: 12 },
        { name: "Edakkal Caves", distance: 15 },
        { name: "Tirunelli Temple", distance: 11 },
        { name: "Pookode Lake", distance: 9 },
        { name: "Chembra Peak", distance: 14 },
        { name: "Banasura Sagar Dam", distance: 13 },
        { name: "Muthanga Wildlife Sanctuary", distance: 16 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Ambalavayal Heritage Museum", distance: 7 }
      ]
    },
    {
      id: "soochipara",
      name: "Soochipara Falls",
      description: "Also known as Sentinel Rock Waterfalls, perfect for trekking and rock climbing.",
      image: "assets/img/falls/soojipara_falls_b_w_wayanad.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    },
    {
      id: "kanthanpara",
      name: "Kanthanpara Falls",
      description: "A picturesque waterfall surrounded by lush greenery and coffee plantations.",
      image: "assets/img/falls/kanta_falls.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Meenmutty Falls", distance: 11 },
        { name: "Soochipara Falls", distance: 9 },
        { name: "Edakkal Caves", distance: 14 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 8 },
        { name: "Banasura Sagar Dam", distance: 15 },
        { name: "Tirunelli Temple", distance: 13 },
        { name: "Muthanga Wildlife Sanctuary", distance: 16 },
        { name: "Wayanad Tea Estate", distance: 10 }
      ]
    }
  ],
  museums: [
    {
      id: "folklore",
      name: "Folklore Museum",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/tirunelli.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    },
    {
      id: "edakkal",
      name: "Edakkal Caves",
      description: "Ancient rock shelter with prehistoric carvings and inscriptions.",
      image: "assets/img/edakkal_caves.webp",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Folklore Museum", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 12 },
        { name: "Meenmutty Falls", distance: 15 },
        { name: "Soochipara Falls", distance: 9 },
        { name: "Pookode Lake", distance: 11 },
        { name: "Chembra Peak", distance: 14 },
        { name: "Tirunelli Temple", distance: 8 },
        { name: "Banasura Sagar Dam", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Muthanga Wildlife Sanctuary", distance: 16 }
      ]
    },
    {
      id: "ambalavayal",
      name: "Ambalavayal Heritage Museum",
      description: "Displays tribal heritage and ancient artifacts from the region.",
      image: "assets/img/tea_wayanad.webp",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    }
  ],
  romantic: [
    {
      id: "karapuzhadam",
      name: "Karapuzhs Dam",
      description: "Karapuzhs Dam.",
      image: "assets/img/falls/meenmufalls.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    },
    {
      id: "PookodeLake",
      name: "Pookode Lake",
      description: "Also known as Sentinel Rock Waterfalls, perfect for trekking and rock climbing.",
      image: "assets/img/falls/soojipara_falls_b_w_wayanad.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Karapuzha Dam", distance: 8 },
        { name: "Banasura Sagar Dam", distance: 11 },
        { name: "Chembra Peak", distance: 13 },
        { name: "Edakkal Caves", distance: 15 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Wayanad Tea Estate", distance: 12 },
        { name: "Muthanga Wildlife Sanctuary", distance: 10 },
        { name: "Folklore Museum", distance: 7 }
      ]
    },
    {
      id: "banasurasagardam",
      name: "Banasurasagar Dam",
      description: "A picturesque waterfall surrounded by lush greenery and coffee plantations.",
      image: "assets/img/falls/kanta_falls.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Karapuzha Dam", distance: 12 },
        { name: "Pookode Lake", distance: 11 },
        { name: "Chembra Peak", distance: 8 },
        { name: "Edakkal Caves", distance: 15 },
        { name: "Meenmutty Falls", distance: 13 },
        { name: "Tirunelli Temple", distance: 9 },
        { name: "Wayanad Tea Estate", distance: 14 },
        { name: "Muthanga Wildlife Sanctuary", distance: 10 },
        { name: "Folklore Museum", distance: 16 },
        { name: "Soochipara Falls", distance: 7 }
      ]
    }
  ],
  plantation: [
    {
      id: "plantation",
      name: "Harissons",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/plantation/tea_plantaion.jpg",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    },
    {
      id: "teaestate",
      name: "Wayanad Tea Estate",
      description: "Expansive tea plantations with guided tours and tasting sessions.",
      image: "assets/img/plantation/tea_estate.webp",
      holidays: "Mon",
      timing: "09:00-17:00",
      Contact: "+91-111 111 1111",
      locationid: "2",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    }
  ],
  trucking: [
    {
      id: "Chundale",
      name: "chundale",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/trucking/edakkal_caves.webp",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    },
    {
      id: "chembra",
      name: "Chembra Peak Trek",
      description: "Popular trekking destination with breathtaking views and a heart-shaped lake.",
      image: "assets/img/trucking/trucking.jpg",
      holidays: "None",
      timing: "06:00-17:00",
      Contact: "+91-222 222 2222",
      locationid: "3",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    }
  ],
  wildlife: [
    {
      id: "Bandipur",
      name: "Bandipur Museum",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/wildlife/Wildlife_safari_at_tholpetty_wildlife_sanctuaryjpg.avif",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    },
    {
      id: "muthanga",
      name: "Muthanga Wildlife Sanctuary",
      description: "Sanctuary with elephants, deer, and a variety of birds in their natural habitat.",
      image: "assets/img/wildlife/pakshipathalam-bird-sanctuary-wayanad.jpg",
      holidays: "None",
      timing: "07:00-17:00",
      Contact: "+91-333 333 3333",
      locationid: "4",
	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    }
  ],
  farms: [
    {
      id: "ambalavayal",
      name: "Ambalavayal",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/tirunelli.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["All Season"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html"
    },
    {
      id: "pepperfarm",
      name: "Pepper Farm",
      description: "Experience spice cultivation and farm life in Wayanad.",
      image: "assets/img/falls/chitafalls.png",
      holidays: "None",
      timing: "08:00-18:00",
      Contact: "+91-444 444 4444",
      locationid: "5",
	  seasontovisit:["All Season"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    }
  ],
  sporting: [
        {
          id: "sporting",
          name: "Sports",
          description: "Ziplines.",
          image: "assets/img/tirunelli.png",
          holidays: "Sun",
          timing: "10:00-18:00",
          Contact: "+91-000 000 0000",
          locationid: "1",
     	  seasontovisit:["Summer (Febuary-May)","Monsoon (June-September)","Winter (October-January)"],
          distance: "10",
          rating:"4.5",
          knowmore: "./knowmore.html",
          nearby: [
            { name: "Edakkal Caves", distance: 7 },
            { name: "Ambalavayal Heritage Museum", distance: 11 },
            { name: "Tirunelli Temple", distance: 14 },
            { name: "Meenmutty Falls", distance: 9 },
            { name: "Pookode Lake", distance: 12 },
            { name: "Chembra Peak", distance: 15 },
            { name: "Banasura Sagar Dam", distance: 8 },
            { name: "Muthanga Wildlife Sanctuary", distance: 13 },
            { name: "Wayanad Tea Estate", distance: 10 },
            { name: "Kanthanpara Falls", distance: 16 }
          ]
      }
    ],
  food: [
    {
      id: "resturants",
      name: "Resturants",
      description: "Showcases the rich cultural heritage and tribal artifacts of Wayanad.",
      image: "assets/img/tirunelli.png",
      holidays: "Sun",
      timing: "10:00-18:00",
      Contact: "+91-000 000 0000",
      locationid: "1",
	  seasontovisit:["All Season"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    },
    {
      id: "localcuisine",
      name: "LocalCuisine",
      description: "Try authentic Kerala dishes at local eateries and food stalls.",
      image: "assets/img/heritage/chain_tree.avif",
      holidays: "None",
      timing: "11:00-23:00",
      Contact: "+91-555 555 5555",
      locationid: "6",
	  seasontovisit:["All Season"],
      distance: "10",
      rating:"4.5",
      knowmore: "./knowmore.html",
      nearby: [
        { name: "Edakkal Caves", distance: 7 },
        { name: "Ambalavayal Heritage Museum", distance: 11 },
        { name: "Tirunelli Temple", distance: 14 },
        { name: "Meenmutty Falls", distance: 9 },
        { name: "Pookode Lake", distance: 12 },
        { name: "Chembra Peak", distance: 15 },
        { name: "Banasura Sagar Dam", distance: 8 },
        { name: "Muthanga Wildlife Sanctuary", distance: 13 },
        { name: "Wayanad Tea Estate", distance: 10 },
        { name: "Kanthanpara Falls", distance: 16 }
      ]
    }
  ],

}